### ISSUE TITLE
Describe how snarkyjs code creates constraints while executed

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/docs2#109]
The dominant paradigm in today's zk tooling is that some user code is _compiled_ to a zk circuit. SnarkyJS, however, works differently: The user-written JS is _executed_ to create a circuit, not compiled.

This difference creates a lot of misconceptions about snarkyjs, for users coming from other zk ecosystems or from higher-level zk material, so we should call it out in the docs to prevent these misconceptions early on.

**Comment by bkase** [comment]
Next steps: Outline of the content

**Comment by bkase** [comment]
Add to FAQ in the short term
