### ISSUE TITLE
Document SnarkyJS permissions

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/docs2#15]
And document use cases:
- I want to prevent tokens from being spent by __, etc
- who can upgrade a smart contract
- how to make it non-upgradeable

**Comment by nicc** [comment]
Indirectly Irresponsible Individual: (@Trivo25 OR @ymekuria) and @jasongitmail 
Backup names are in case Florian or Yoni pick up this work.
(F || Y) to support technically and Jason to sign off and merge.

**Comment by Trivo25** [comment]
Where should this live? Advanced SnarkyJS/Permissions?

**Comment by jasongitmail** [comment]
@Trivo25 Probably. Should we mention it very briefly on the [How to Write a zkApp page](https://docs.minaprotocol.com/zkapps/how-to-write-a-zkapp), since it seems fundamental, and link from there to the full details where you suggested? IMO, that's probably ideal to keep the How to Write a zkApp page shorter & highlight permissions as it's own section, given the importance.

**Comment by mitschabaude** [comment]
> @Trivo25 Yeah, probably ideal. Should we mention it very briefly on the [How to Write a zkApp page](https://docs.minaprotocol.com/zkapps/how-to-write-a-zkapp), since it seems fundamental, and link from there to the full details where you suggested? IMO, that's probably ideal to keep the How to Write a zkApp page shorter & highlight permissions as it's own section on `Advanced SnarkyJS/Permissions`, given the importance.

That sounds like a good idea, in fact there's already sort of a hint at permissions in How to write a zkApp, which would greatly benefit from that link to the advanced section: [At the end of this section](https://docs.minaprotocol.com/zkapps/how-to-write-a-zkapp#signing-transactions-and-explicit-account-updates)
