### ISSUE TITLE
[Tutorial 6] - Incorrect node command for running `storageServer`

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/docs2#190]
In the [following section,](https://docs.minaprotocol.com/zkapps/tutorials/offchain-storage#running-our-project) a user reported that the tutorial prompts the user to install `experimental-zkapp-offchain-storage` but then to run `node node_modules/zkapp-offchain-storage/build/src/storageServer.js`. This command is seemingly incorrect and should be fixed to `node node_modules/experimental-zkapp-offchain-storage/build/src/storageServer.js`

**Comment by barriebyron** [comment]
this error no longer exists, closing
