### ISSUE TITLE
Wrong line numbers for main.ts in Tutorial 6. Does it link to the correct version?

### ISSUE THREAD

**Issue by garyrob** [o1-labs/docs2#195]
The line "async function updateTree()" is at line 106 in https://github.com/es92/zkApp-examples/blob/f65d61e8884691d2cd62b59e1e21568bd6f119a7/06-offchain-storage/contracts/src/main.ts, which is the version linked to on the page https://docs.minaprotocol.com/zkapps/tutorials/offchain-storage. But that documentation page says that that function is at line 120. Also, the displayed section of the source code on that documentation page shows the line being 120. 

At this point, I don't know whether the documentation is wrong, or whether the link on https://docs.minaprotocol.com/zkapps/tutorials/offchain-storage is to the wrong version of the source file.

**Comment by mitschabaude** [comment]
docs are probably gone out of sync with the source file

**Comment by mitschabaude** [comment]
we're working on having these tutorials synced to working code in a more automatic way: https://github.com/o1-labs/docs2/issues/187

**Comment by mitschabaude** [comment]
cc @nicc we should fix this as part of our tutorials fixing work
