### ISSUE TITLE
Confirm this repo is setup to disallow PRs to be merged if build isn't successful

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/docs2#213]
Test and confirm because it's unclear if build's must succeed before merging is allowed.

We have this repo setting:
<img width="786" alt="Screenshot 2023-01-04 at 6 30 00 PM" src="https://user-images.githubusercontent.com/50032291/210557959-807dcb7d-2e4b-4c07-ac72-898091a9213e.png">

And it appears that the Vercel build adds a status check:
<img width="867" alt="Screenshot 2023-01-04 at 6 31 41 PM" src="https://user-images.githubusercontent.com/50032291/210558127-eb6b5aff-d300-4378-a9de-f31fb32df23c.png">

It seems it should work, but let's test it.

**Comment by rjdellecese** [comment]
It's confusing, but you have to click into that search box in the first screenshot and manually select _which_ status checks should prevent merging if they aren't successful.

**Comment by rjdellecese** [comment]
(I was confused by this myself literally two weeks ago)

**Comment by jasongitmail** [comment]
Oh nice, ty! I was expecting to see a dropdown of options, which never appeared. But if I start typing `Ver...`, it does show matching options! 

Updated in the repo settings. Let's give this a try
<img width="483" alt="Screenshot 2023-01-06 at 2 48 08 AM" src="https://user-images.githubusercontent.com/50032291/210879429-3b723153-f480-4d41-95f8-58aec8c7c527.png">

**Comment by rjdellecese** [comment]
Ah right, that must have been what got me too. I just remember being confused by it. Hopefully that works!

**Comment by jasongitmail** [comment]
Closing because I think this is solved. Can reopen if not.
