### ISSUE TITLE
Code blocks: Make line numbers and `$` non-selectable

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/docs2#248]
When a reader uses their mouse to select code to copy & paste it, the line numbers are copied as well. Similarly `$` is copied for terminal commands. The ideal UX would be to make these non-copyable. 
  
![image](https://user-images.githubusercontent.com/50032291/213551635-93ee88a3-4ebb-495d-a379-54b6e670875e.png)

If Docusaurus gives us the flexibility, or if we're able to accomplish this using JS to target the code blocks, we may be do this using CSS (`user-select: none`)

If we're adding spans around these, could we add two separate classes to each please (such as code-terminal-prefix, code-line-numbers) so we can style them? This would let us make the `$` gray to de-emphasize it, and maybe the line numbers similarly. But two classes gives us flexibility if we choose different styles.

**Comment by barriebyron** [comment]
line numbers and command line prompt are not selected, this work is complete
