### ISSUE TITLE
[Tutorial 4]: transaction error at mina.sendTransaction

### ISSUE THREAD

**Issue by deadblackclover** [o1-labs/docs2#252]
When implementing an application using Tutorial 4, I get an error at the transaction sending stage:

`{message: "transaction error"}`

The error occurs when I try to confirm a transaction in Auro Wallet (V2.1.4).

I also noticed that in zkapp_command.json feePayer has a different public key than the one set in the wallet.

zkapp_command.json
```json
{
  "feePayer": {
    "body": {
      "publicKey": "B62qiTKpEPjGTSHZrtM8uXiKgn8So916pLmNJKDhKeyBQL9TDb3nvBG",
      "fee": "0",
      "validUntil": null,
      "nonce": "0"
    },
...
```

For the sake of experimentation, I used the test application from Auro Wallet and got exactly the same error at the confirmation stage.

https://github.com/aurowallet/auro-test-dapp-berkeley

Also in the tutorial, the address given is `B62qrBBEARoG78KLD1bmYZeEirUfpNXoMPYQboQTwqmGLtfqAGLXdWpU` does not exist in the Berkeley network. I was forced to deploy the contract myself.

My zkApps: `B62qryuP9Chkym13eSzo1RqEv2rmq62ufEFqt71naBZkyXJqpkPe3y7`

Application code:
https://github.com/deadblackclover/04-zkapp-browser-ui/blob/main/ui/pages/_app.page.tsx

**Comment by ymekuria** [comment]
Thanks for bringing this up @deadblackclover. We will look into this.
