### ISSUE TITLE
Update page about deprecated client-sdk, to mention current mina-signer instead

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/docs2#259]
Because the Node operators section hasn't been rewritten, [this page](https://docs.minaprotocol.com/node-operators/client-sdk) now refers to the now deprecated [@o1labs/client-sdk](https://www.npmjs.com/package/@o1labs/client-sdk), and should be updated to the current [mina-signer](https://www.npmjs.com/package/mina-signer). 

- [ ] The entire page and path needs to be updated approriately, not just update of links. 
- [ ] We should also redirect the old page URL to the new one as well.

**Comment by barriebyron** [comment]
https://docs.minaprotocol.com/node-operators/mina-signer updated

more work to do in https://app.zenhub.com/workspaces/zkapps-product-eng-6130fedb3b0fc600123d8796/issues/gh/o1-labs/docs2/544
