### ISSUE TITLE
Document how to set any fields on the account that are not yet documented

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/docs2#262]
@mitschabaude Can you list which these are to clarify please?

**Comment by mitschabaude** [comment]
Everything except state is not documented right now!

We have a unified API for them, which is what we'll want to document:
```ts
this.account.<field>.set(value); // on SmartContract

accountUpdate.account.<field>.set(value); // on any account update
```

**Comment by mitschabaude** [comment]
`field` is one of the update fields, except `appState`:
https://github.com/o1-labs/snarkyjs/blob/756733f8e5edc91d2f84d36e9c4dc77001c2c9ac/src/provable/gen/transaction.ts#L112-L157

**Comment by mitschabaude** [comment]
The docs for this will be simple -- it's just like `this.x.set(..)` for state, which we already described. could be added to the existing on-chain values section maybe, as a new sub-header "setting account fields"?
