### ISSUE TITLE
Document UI project creation

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/docs2#271]
We need to document the option to create Svelte Kit, NextJS, and NuxtJS projects in:
- https://docs2-git-zkapp-roadmap-minadocs.vercel.app/zkapps/how-to-write-a-zkapp and
- https://docs2-git-zkapp-roadmap-minadocs.vercel.app/zkapps/how-to-write-a-zkapp-ui

**Comment by nicc** [comment]
Indirectly Irresponsible Individual: @jasongitmail
