### ISSUE TITLE
Update time-locked tokens graphic 

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/docs2#285]
On this page: https://docs.minaprotocol.com/zkapps/advanced-snarkyjs/time-locked-accounts 

To use this new graphic from Damian:
![PRD2023002_Time_locked_accounts_graph_v3_lightBG](https://user-images.githubusercontent.com/50032291/224332694-7a39e452-943b-42f2-ae23-9d102ac07895.png)

**Comment by iregina** [comment]
The fix is made for #305
