### ISSUE TITLE
Docs incorrectly include time-bound content [zkApp Developers section]

### ISSUE THREAD

**Issue by nicc** [o1-labs/docs2#287]
In order to create [timeless documentation](https://developers.google.com/style/timeless-documentation), we want to avoid temporally relative statements.

This issue applies to the [zkApp Developers](https://docs.minaprotocol.com/zkapps/tutorials/hello-world#) section of the docs.

See issue #286.

It excludes Node Operator-related sections as these are undergoing improvement separately. We will want to address time-bound content there too eventually but now is not the time.

**Comment by nicc** [comment]
@barriebyron has already proposed some of this work [here](https://github.com/o1-labs/docs2/pull/251)

**Comment by nicc** [comment]
Indirectly Irresponsible Individual: @jasongitmail

**Comment by barriebyron** [comment]
Remove content like:

We will be adding blockchain-specific testing functionality in the future. Keep an eye on this section for updates.
