### ISSUE TITLE
Docs do not use the evergreen Discord invite link to the Mina Protocol server [zkApp Developers section]

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/docs2#294]
Docs do not consistently use the standard evergreen Discord invitation link to the Mina Protocol server. 

Now that the Mina Discord server has an [evergreen invite](https://discord.gg/minaprotocol) link `https://discord.gg/minaprotocol` it's time to use it everywhere. We can build trust and reliability by removing the possibly expired and inconsistent invite links that are scattered throughout the docs.

This issue applies only to the [zkApp Developers](https://docs.minaprotocol.com/zkapps/tutorials/hello-world#) section of the docs.

Companion issue #293 

Excluded are the Node Operator-related sections, as these sections are undergoing improvement separately. We will also want to address tense in the content there eventually but now is not the time.

**Comment by nicc** [comment]
Indirectly Irresponsible Individual: @jasongitmail

**Comment by nicc** [comment]
Indirectly Irresponsible Individual: @jasongitmail

**Comment by barriebyron** [comment]
see the work PR https://github.com/o1-labs/docs2/pull/317

**Comment by barriebyron** [comment]
closed in https://github.com/o1-labs/docs2/pull/323
