### ISSUE TITLE
Run through Tutorial 1: Hello World 

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/docs2#295]
Fresh eyes happen only once. 
Test the docs, note opportunities and friction, and develop user empathy. 
This issue scope includes [Tutorial 1: Hello World](https://docs.minaprotocol.com/zkapps/tutorials/hello-world) 

This issue output can then be evaluated for possible improvements, if any.

**Comment by nicc** [comment]
IRI: @nicc
