### ISSUE TITLE
Automate creation of a single page of zkApp & SnaryJS content for Chap GPT, et al

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/docs2#321]
At `/onepage`because this is easy to remember? 

Downside is it is not clear that this is just zkApps related, but we could solve this with a banner added to the page to clarity the intended usage of this page. `/zkappsonepage` is another option, but that is inconvenient to type and likely to reduce usage.

**Comment by nicc** [comment]
Our docs live as markdown.
We want to compile and concatenate this content into a single page in a CI job that can be fed to chatGPT.
It does not need to look good..

**Comment by MartinMinkov** [comment]
Does this need to be an actual web page rendered, or can it just be a file in the project repo that can be fed into an AI tool? cc @jasongitmail

**Comment by jasongitmail** [comment]
@MartinMinkov IMO, it'll be most useful to others if it's accessible at a URL like `/onepage` that is easy to remember and tell people about at conferences, etc, rather than them needing to visit the docs repo, find the file, select raw, and copy it. 

Let's not include it in the sidebar though for now
