### ISSUE TITLE
Replace email signup form in footer to support Google Analytics

### ISSUE THREAD

**Issue by nicc** [o1-labs/docs2#322]
We'd like to get Google Analytics tracking implemented on the email form in the footer of Docs. 

The form should change from this:
```html
<form class="minaFooterform__submitContainer_q033">
    <input type="email" name="email" id="email" placeholder="Enter Email" class="minaFooter_form_input_OKq" value="">
    <button type="button" class="minaButtonOrange_IDUQ">
        <span>Submit</span>
        <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path d="M3 7h10v1H3zM11 6h1v1h-1zM10 5h1v1h-1zM9 4h1v1H9zM10 9h1v1h-1zM9 10h1v1H9zM11 8h1v1h-1z"></path>
        </svg>
    </button>
</form>
```

To this:
```html
<form class="minaFooterform__submitContainer_q033" id="newletter_form" action="
https://minaprotocol.com/docs-footer-subscribe" enctype="application/x-www-form-urlencoded" method="post" >
    <input type="email" name="email" id="email" placeholder="Enter Email" class="minaFooter_form_input_OKq">
    <button type="submit" class="minaButtonOrange" onclick="document.getElementById('newletter_form').submit();">
        <span>Submit</span>
        <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path d="M3 7h10v1H3zM11 6h1v1h-1zM10 5h1v1h-1zM9 4h1v1H9zM10 9h1v1h-1zM9 10h1v1H9zM11 8h1v1h-1z"></path>
        </svg>
    </button>
</form>
```

For the submissions to work, we're having to move away from the regular button to a submit type. That means that the attached CSS styles will also need to be added to the docs site.

[https://app.zenhub.com/files/368694740/abe54555-e429-4748-afaa-cb281b81e3fe/download](https://app.zenhub.com/files/368694740/abe54555-e429-4748-afaa-cb281b81e3fe/download)

[https://app.zenhub.com/files/368694740/7b9feb9a-f70c-47bb-9d40-7d2b2d45612d/download](https://app.zenhub.com/files/368694740/7b9feb9a-f70c-47bb-9d40-7d2b2d45612d/download)

**Comment by barriebyron** [comment]
related to https://github.com/o1-labs/docs2/issues/83

**Comment by nicc** [comment]
IRI: @nicc

**Comment by nicc** [comment]
Further info for debugging and testing can be found [here](https://docs.google.com/document/d/1s9rZte84xjwJh9TjlTwqjg7VgxYhXIXH6nFtGcJH0hc/edit#)
