### ISSUE TITLE
Fix automated tutorial check script

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/docs2#324]
The re-addition of the interaction `zk project` dropdown to allow a dev to choose which UI project scaffolding, if any, they want, caused this. 

```
### Executing 'zk project 01-hello-world'…

25l? Create an accompanying UI project too? … 
▸ next
  svelte
  nuxt
  empty
Error: The operation was canceled.
```
See this [build error on this docs PR](https://github.com/o1-labs/docs2/actions/runs/4480945793/jobs/7876944488?pr=323).

**Comment by barriebyron** [comment]
thanks for reporting this issue @jasongitmail 
I'm not clear how I can help @ymekuria  but hit me up to let me know
