### ISSUE TITLE
Docs do not use consistent pronouns [zkApps]

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/docs2#331]
To follow a consistent voice and tone, we want our technical documentation to use consistent pronouns. In most cases, we want to use "you" as the reader. While I was working on #288 and #289 the required tense updates overlapped with these pronoun opportunities. (I did try to limit my scope, and was successful is most cases).

The docs today mix and match how we talk to our readers. Docs do not use consistent pronouns, so we have a variety of actors (you, we, I, us, and so on). 

Most of the docs already do this, but where necessary, let's replace inconsistent [personal pronouns](https://developers.google.com/style/pronouns?hl=en#personal-pronouns) with the second person _you_

It makes sense to combine the personal pronoun updates with the required attention to address the [Ambiguous pronoun references](https://developers.google.com/style/pronouns?hl=en). 

We want to improve readability and comprehension by ensuring that a pronoun clearly refers to its antecedent (the noun that the pronoun is replacing). 

We want to avoid vague and confusing references between a pronoun and its antecedent (naked "this" and the naked "that"). For example, the subject of "this" is ambiguous in these (and many other) instances:

> This means that the 
> Because of this, when 
> This has some implications
> This would lead to 
> This will generate 

This issue will likely be done in sections, but based on my experience with earlier updates, I do not want to define the sections yet. Let's talk more about these improvement efforts. @jasongitmail

**Comment by jasongitmail** [comment]
+1, especially on `you`

I'll be curious to see how the 'this' will be resolved though. I can see the intention, but wonder if the end result may read forced in some cases. But worth trying!

**Comment by barriebyron** [comment]
iterative updates to our docs have addressed the pronoun work in PRs like https://github.com/o1-labs/docs2/pull/432
