### ISSUE TITLE
Add updated time-locked accounts graphic

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/docs2#354]
Removes arrow from left of purple line on the cliff portion, at Gregor's suggestion.

To update on the https://docs.minaprotocol.com/zkapps/advanced-snarkyjs/time-locked-accounts page. 

![PRD2023002_Time_locked_accounts_graph_v3_lightBG-edited](https://user-images.githubusercontent.com/50032291/231478289-f896eb58-733b-4cdb-9c77-e5cc275252a3.png)

**Comment by barriebyron** [comment]
Oh good, we have a teaching moment! @jasongitmail how do I get the image from https://user-images.githubusercontent.com/50032291/231478289-f896eb58-733b-4cdb-9c77-e5cc275252a3.png to the `img` directory?

**Comment by barriebyron** [comment]
I'll do this work as part of https://github.com/o1-labs/docs2/issues/287 for the ongoing zkApp edits for timeless docs (no relation to the time-locked content here)

**Comment by barriebyron** [comment]
a ha! solution, just save as for the image (so easy I missed it!)

**Comment by barriebyron** [comment]
image is updated in https://github.com/o1-labs/docs2/pull/355/ (although, tbh, I can't see a difference)
