### ISSUE TITLE
Docs: SnarkyJS does not have its own section

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/docs2#357]
From @mitschabaude [convo in Slack](https://o1-labs.slack.com/archives/C02DSGWNQNA/p1681745521879269)

Hey docs writers! I've been thinking a bit about how we could improve our SnarkyJS docs. I'm not really happy with how the docs are structured right now. (I've brought some of this up in the past)
Currently, we have the following:
- SnarkyJS introductionary docs, which are buried inside a single long page that's called _How to write a zkApp_ and has to share its space with installation instructions for the zkapp-CLI
- A section called "Advanced SnarkyJS"
- The SnarkyJS API reference

... with this structure there's no good place to add "basic SnarkyJS docs" -- stuff that everyone should read. There's also no good link which can be used as the entry point -- i.e., "click here to read the SnarkyJS docs" (the best link right now is a subsection of How to write a zkApp, but I think this deserves its own page.)
A second problem which I see as connected with the first one is that the docs are lacking some pretty fundamental topics:
- A proper explanation of how to write circuits, which people fail to understand again & again
  - detailed breakdown of what works & doesn't work is missing
  - core functionality (slightly advanced) like `Circuit.witness` is not covered
- What SnarkyJS does under the hood, except one FAQ entry

What we need is simply a supersection SnarkyJS, which is the place to add basic docs. And then within that we could have more advanced topics in a subsection, or just near the end of the SnarkyJS section

```
zkApp developers
  - Overview
  - How zkApps Work
  - How to Write a zkApp // contains current "Getting started" content, but links to SnarkyJS > Introduction for the SnarkyJS content
  - How to Test a zkApp
  - How to Deploy a zkApp
  - How to Write a zkApp UI
  - SnarkyJS
    // the topics currently covered by "How to write a zkApp"
    - Introduction
    - Writing circuits
    - Smart contracts
    - Interacting with Mina
    // the topics currently covered by "Advanced SnarkyJS"
    - ...
  - Tutorials
  - SnarkyJS Reference
  - Roadmap
  - FAQ
```

**Comment by nicc** [comment]
I like the suggestion! 

Some thoughts:
- The How To … sections seem related enough to collapse under a common heading. They all seem to fit under "How zkApps work." If we don’t mind the nesting that could be cleaner than having granular how-tos alongside a subsection on SnarkyJS
- I’d put writing a UI before testing and deploying. I think it'll only become more important and this way it's less of an afterthought
- The API Reference should probably go under SnarkyJS (I may be unaware of some technical limitations since I believe the reference is generated from doc comments)
- The Advanced SnarkyJS section is important but kinda feels like a list of disparate low-level topics. Maybe we can consider reframing them according to goals and intentions. Other items like "Writing circuits" under the proposed SnarkyJS section are good exmaples of this. My thougthts on this are still a bit speculative and hand-wavy. Will think on it before we discuss.

This would end up look something like this:

> zkApp developers
>   - Overview
>   - How zkApps Work
>     - Overview
>     - How to Write a zkApp // contains current "Getting started" content, but links to SnarkyJS > Introduction for the SnarkyJS content
>     - How to Write a zkApp UI
>     - How to Test a zkApp
>     - How to Deploy a zkApp
>   - SnarkyJS
>     - Overview // the topics currently covered by "How to write a zkApp"
>     - Introduction
>     - Writing circuits
>     - Writing smart contracts
>     - Interacting with Mina
>     // the topics currently covered by "Advanced SnarkyJS" (potentially reframed to achieve goals)
>     - ...
>     - API Reference
>   - Tutorials
>   - Roadmap
>   - FAQ

**Comment by mitschabaude** [comment]
> The How To … sections seem related enough to collapse under a common heading. They all seem to fit under "How zkApps work." If we don’t mind the nesting that could be cleaner than having granular how-tos alongside a subsection on SnarkyJS

+1

**Comment by barriebyron** [comment]
@nicc  I wave back at your hand-wavy suggestions, good approach

The page title "Overview" has low value for many reasons: 
- ambiguous search results
- results in ambiguous links to the highest value page

Perhaps out of scope of this restructuring effort, but let's think ahead to a time when "Overview" pages can be replaced with a self-titled "hey, I know what this is!" home page for each section as requested in https://github.com/o1-labs/docs2/issues/343

**Comment by barriebyron** [comment]
inspiration 
https://ethereum.org/en/developers/docs/ 

separate how-to content from explainer content https://documentation.divio.com/

leave overview > rename to zkApps Overview

zkApp developers
> 
> zkApps Overview
> About zkApps (keep as is)
>   How to Write a zkApp // contains current "Getting started" content, but links to SnarkyJS > Introduction for the SnarkyJS content
>   How to Write a zkApp UI
> How to Test a zkApp
> How to Deploy a zkApp
> SnarkyJS
> Overview // the topics currently covered by "How to write a zkApp"
> Introduction
> Writing circuits
> Writing smart contracts
> Interacting with Mina
> // the topics currently covered by "Advanced SnarkyJS" (potentially reframed to achieve goals)
> ...
> API Reference
> Tutorials
> Roadmap
> FAQ

**Comment by barriebyron** [comment]
before restructure
<img width="296" alt="image" src="https://user-images.githubusercontent.com/10067215/234984224-38fd46fb-d22b-4cd5-82e2-a4baef83b3bf.png">

**Comment by mitschabaude** [comment]
done!
