### ISSUE TITLE
Remove await isReady from tutorials

### ISSUE THREAD

**Issue by nicc** [o1-labs/docs2#389]
Adding details here

Scope is for all tutorials: remove isReady and shutdown and run through tutorial with updated code to make sure everything works as expected 

Feedback from from @qwadratic in tutorial test:

> In all sample projects isReady and shutdown functions are used, but deprecated. Respectively, lines of code with imports and calls to these functions should be deleted. The PR for this exists, but only one tutorial fixed. Will another contributor finish that or should I do it?

yes please, @qwadratic  your contributions and fixes are most welcome! Be sure to check open issues and open PRs for best async update success. Questions? please ask

**Comment by barriebyron** [comment]
I am running through the final Interacting with zkApps server-side tutorial. 
The prerequisites are to complete Tutorial 1: Hello World and Tutorial 3: Deploy to a Live Network 
I'm running through Tutorial 1: Hello World and see that the import statement shows strikethroughs

Based on work that closed https://github.com/o1-labs/o1js/issues/674 (doing a little detective work, I see updates that remove isReady, shutdown from src/build/run.js), it looks like example code in https://github.com/o1-labs/docs2/blob/main/examples/zkapps/01-hello-world/src/main.ts needs updating.

**Comment by barriebyron** [comment]
looks like other tutorials also need updating, like https://github.com/o1-labs/docs2/blob/main/examples/zkapps/interacting-with-zkApps-server-side/src/main.ts
