### ISSUE TITLE
Add "Beta" or "Experimental" tag in documentation, for topics like keccak+ECDSA

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/docs2#450]
From @stevenpack 

> The crypto team doesn't characterize ECDSA+keccak as "production hardened" yet, but we want to get into the hands of our users to get usability and performance feedback. We should make this clear in the docs. If we don't already have it, please introduce the concept of tagging a feature as "beta" and start with ECDSA. (or if we already have an existing lifecycle type of annotation, please use that).

See the original issue with comment threads 

https://github.com/o1-labs/zkapp-cli/issues/440#issuecomment-1603468945 was inadvertently created in a different repository

**Comment by barriebyron** [comment]
@stevenpack wdyt about using Experimental instead of Beta?

I am familiar with this hierarchy of feature labels that set expectations with our users: 
1) Experimental 
2) Beta 
3) GA (what we call production hardened)

https://handbook.sourcegraph.com/departments/engineering/product/process/gtm/beta_and_experimental_feature_labels/ 

I like the idea of having a docs topic similar to 
https://docs.sourcegraph.com/admin/beta_and_experimental_features 
with guidance to ask questions and provide feedback in Discord

**Comment by barriebyron** [comment]
use the info box explaining experimental

**Comment by barriebyron** [comment]
new topic see proposed new topic https://github.com/o1-labs/docs2/pull/563

**Comment by garwalsh** [comment]
@barriebyron Can we implement the tag as an info box or callout as you suggested above?
![image](https://github.com/o1-labs/docs2/assets/15691177/2a4f55cc-c930-4dfc-a404-34b15b80dd3c)

**Comment by barriebyron** [comment]
@MartinMinkov will know what our options are for implementing an experimental callout in docs. In Docusaurus, the callout is called an admonition https://docusaurus.io/docs/markdown-features/admonitions

The Markdown syntax for the built-in _preset-classic_ callouts is documented in our docs style guide https://github.com/o1-labs/docs2/wiki/Markdown-Syntax#callouts 

Martin, could we customize admonitions to add an Experimental type? per https://docusaurus.io/docs/markdown-features/admonitions#customizing-admonitions 

Also, could we change the green color in the TIP callout? to some other color like lavender to go along with MF theme

**Comment by barriebyron** [comment]
https://github.com/o1-labs/docs2/pull/571/files for the requested text update and removing from sidebar (great idea from Maki so our readers don't arrive at the page w/o context)

@MartinMinkov tells us:

> If we wanted to customise this behavior, it's very quick to do. I'd estimate this to be pretty fast to do, no more than a 2 for our sprint planning. It's even easier if we just use one of the shipped ones!

**Comment by MartinMinkov** [comment]
https://github.com/o1-labs/docs2/pull/563 is merged, is this issue okay to close? @barriebyron

**Comment by barriebyron** [comment]
@MartinMinkov  we talked about admonition enhancement... is this the issue to track that work in? or did I lost track and we have another issue, or we need another issue?
 thanks for helping me keeping this enhancement request straight and alive

**Comment by MartinMinkov** [comment]
Will follow up with a admonition enhancement to our front end!
