### ISSUE TITLE
Document the Lightweight Mina networks

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/docs2#452]
The Mina protocol, while powerful and innovative, lacks a simple and efficient way to deploy and run local networks for testing purposes. Developers must use expensive cloud solutions or set up everything locally, both of which can be slow and resource-intensive.

The Dockerization of lightweight Mina local networks aims to address these challenges by providing a lightweight, fast, and resource-efficient solution for spinning up local Mina networks. Docker image allows developers to easily test their applications and changes against a "close to real" Mina network.

Docker image allows users to spin up a Mina local network

---

@shimkiv provided this content:

## Title

Spin up lightweight Mina network within single container.

## Description

Corresponding [RFC](https://github.com/o1-labs/rfcs/blob/main/0004-dockerised-local-network.md).  

Every Docker Image is packaged with the `Genesis Ledger` configuration that contains more than `1k` pre-funded accounts (with balances of `155 MINA` each).  

We also added helper tool inside the Docker Image, called `Mina Accounts-Manager`, in order to let users retrieve account information to work with in automated way.  
Example use case of this application might be in executing parallel automated tests against the `lightweight Mina network`.  
Because such a tests supposed to be isolated and should never impact work/env. of each other, there must be a way to get `unused` accounts at any particular point in time. This is the main purpose of the `Mina Accounts-Manager`.  
P.S. Don't forget to release used accounts after you're done to keep the accounts pool available for other tasks.  

This Docker Image also exposes the `8080` port, which is served by the Nginx reverse proxy with proper `CORS` management and passes requests to one of the Mina Daemon's `GraphQL` endpoints available.  
It is very important to use endpoint like `http://localhost:8080/graphql` in order to communicate with the Mina GraphQL endpoint so that the `SnarkyJS` applications can work without any additional env. configuration.

## Usage

**Single-Node**:  

```shell
docker run -it --env NETWORK_TYPE="single-node" --env PROOF_LEVEL="none" -p 3085:3085 -p 8080:8080 -p 8181:8181 us-west1-docker.pkg.dev/o1labs-192920/mina-local-network/mina-local-network:rampup-latest-lightnet
```  

**Properties**:  
- Transaction finality (`k`) in `30` blocks.
- `720 slots` per `epoch`.
- New blocks production every `~20-40` seconds.
- `5-8` transactions per block.
- `~625-650Mb` of RAM consumption (after initial spike and if stays alive during less than `2hrs` ~= `1/2 epoch`).
- The startup and sync time `~1-2` minutes.  

---

**Multi-Node**:  

```shell
docker run -it --env NETWORK_TYPE="multi-node" --env PROOF_LEVEL="none" -p 4001:4001 -p 4006:4006 -p 5001:5001 -p 6001:6001 -p 8080:8080 -p 8181:8181 us-west1-docker.pkg.dev/o1labs-192920/mina-local-network/mina-local-network:rampup-latest-lightnet
```  

**Properties**:  
- Transaction finality (`k`) in `30` blocks.
- `720 slots` per `epoch`.
- New blocks production every `~20-40` seconds.
- `5-8` transactions per block.
- `~5.5-6+Gb` of RAM consumption.
- The startup and sync time `~4-6` minutes.  

---

**Available image tags**:

- `rampup-latest-lightnet`
- `berkeley-latest-lightnet`
- `develop-latest-lightnet`

---

**Mina Accounts-Manager** (runs inside the container if application was packaged with image):  

```shell
-----------------------------
.:: Mina Accounts-Manager ::.
-----------------------------

Application initialized and is running at: http://localhost:8181
Available endpoints:

   HTTP GET:
   http://localhost:8181/acquire-account
   Supported Query params: isRegularAccount=<boolean>, default: true
                           Useful if you need to get non-zkApp account.
   Returns Account JSON:
   { pk:"", sk:"" }

   HTTP PUT:
   http://localhost:8181/release-account
   Accepts Account JSON as request payload:
   { pk:"", sk:"" }

Operating with:
   Mina Genesis ledger:   /root/.mina-network/mina-local-network-2-1-1/daemon.json
   Mina GraphQL endpoint: http://localhost:8080/graphql
```

**Comment by shimkiv** [comment]
Also related to https://github.com/o1-labs/snarkyjs/issues/981

**Comment by barriebyron** [comment]
from Slack convo
https://o1-labs.slack.com/archives/C02DSGWNQNA/p1688059229032469 
From sprint review convo, reminder to take a step back and think about the perfect workflow and then how the Docker image fits and what we do with it; get Steve and Maki involved
we'll want a new topic in the docs, but where?
Questions to help us determine where to publish this content:
who is the target audience? which developers? node developers? (not specifically zkApp devs?)
fast and simple way for developers to run the Mina blockchain networks locally.
is this Docker image an alternative - or replacement? - to the setting up a Mina node steps in Getting Started? https://docs.minaprotocol.com/node-operators/getting-started  we could link from here (but does this Node Operators section placement exclude other devs?)
is Docker a one-and-done? or we'll need upgrade steps to fetch updated images when they come out? or the image auto-updates?
is this information related at all to the (sparse) mention of Docker for Node Operators to get started with Mina? https://docs.minaprotocol.com/node-operators/getting-started#docker

**Comment by barriebyron** [comment]
I created a hackmd.io document to enable collaboration for this doc without adding to our docs repo

https://hackmd.io/@poEpGz7_SSmeud49YUGchg/ry9WBdeYn/edit

**Comment by barriebyron** [comment]
Consider https://docs.minaprotocol.com/zkapps/snarkyjs/interact-with-mina

> Apart from Mina.Metwork, you can also use a mocked "Mina instance" for local testing:
> ```
> const Local = Mina.LocalBlockchain();
> Mina.setActiveInstance(Local);
> ```

https://docs.minaprotocol.com/zkapps/snarkyjs/interact-with-mina

**Comment by shimkiv** [comment]
I think we can close this one. Documentation for public Docker Hub repo is well defined and managed [here](https://github.com/o1-labs/mina-lightnet-docker/blob/develop/DockerHub.md).
