### ISSUE TITLE
Tutorial 4 Hardcoded zkApp address is not deployed

### ISSUE THREAD

**Issue by duncand0nuts** [o1-labs/docs2#455]
Tutorial 4 has a hardcoded zkApp address (B62qiqD8k9fAq94ejkvzaGEV44P1uij6vd6etGLxcR4dA8ZRZsxkwvR) in it which has been wiped during a redeploy. Following the tutorial now gives an error when trying to interact via Auro wallet with the zkApp.

We could edit this so that users either deploy their own zkApp, or give them a new zkApp address to use which is live.

**Comment by ymekuria** [comment]
@duncand0nuts I'm working updating the code for tutorial 4. I will change this.
