### ISSUE TITLE
Update Footer to match minaprotocol[dot]com

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/docs2#489]
Tasks:
- Change copyright section to (c) 2023 Mina Foundation. All rights reserved.
- All the linked items are out of date - update to match that of the [minaprotocol.com](http://minaprotocol.com/) footer
- Also calling out that we added a link to the new Mina Foundation site under Ecosystem

**Comment by LucidSamuel** [comment]
@MartinMinkov, could you please clarify your statement about "update to match"? Are you referring to applying all the changes, such as replacing the "Community" header with "Ecosystem" and updating the sub-links to match those on the Mina protocol website? Additionally, do you intend to replicate the documentation footer to fully match that of the Mina protocol website?

**Comment by barriebyron** [comment]
@LucidSamuel  has all of this work has been done in https://github.com/o1-labs/docs2/pull/531 ? If so we can close this issue

thank you for the updates
