### ISSUE TITLE
Link to mina-local-network Docker image from How To Test Your zkApp

### ISSUE THREAD

**Issue by nicc** [o1-labs/docs2#509]
At this point we just want to make people aware that it exists. More deeply integrated documentation of the workflow will follow.

Here's the Docker image: https://hub.docker.com/r/o1labs/mina-local-network

And this is the docs page to link from: https://docs.minaprotocol.com/zkapps/how-to-test-a-zkapp

**Comment by barriebyron** [comment]
https://github.com/o1-labs/docs2/pull/527

**Comment by barriebyron** [comment]
The updated Docker Hub image text is up for review by @Serhii Shymkiv https://hackmd.io/TPlu6kYUR4WQD5IGRWUsDw?view
