### ISSUE TITLE
bug: Tutorial 6 project setup fails on the npm install experimental-zkapp-offchain-storage --save step

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/docs2#564]
following steps in this doc https://docs.minaprotocol.com/zkapps/tutorials/offchain-storage#project-setup 
 this command fails:
`npm install experimental-zkapp-offchain-storage --save`

the experimental-zkapp-offchain-storage package is on a much older version of snarkyjs. It probably has to be updated
- having a separate npm package is not a good idea
- consider making the experimental package inline into the docs repo.
- alternatively, we fix its snarkyjs version, but then we need to make sure there aren't two snarkyjs versions that interact in conflicting ways (for example: using different snarky global states)

**Comment by MartinMinkov** [comment]
Should be fixed with this PR:
https://github.com/o1-labs/docs2/pull/568

The library is installed with:
`npm i experimental-offchain-zkapp-storage`

**Comment by barriebyron** [comment]
thanks @MartinMinkov  for the fix in https://github.com/o1-labs/docs2/pull/568
