### ISSUE TITLE
add steps to Tutorial 9 to run the code 

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/docs2#628]
We merged https://github.com/o1-labs/docs2/pull/625 for the [Recursion tutorial](https://docs.minaprotocol.com/zkapps/tutorials/recursion) doc updates

There are no steps in this tutorial, so I wasn't able to follow instructions to verify the code.

This issue raises visibility to the need to verify the code runs with o1js 0.13.1

I suggest that we add steps to execute this code so the tutorial reader has a path forward

**Comment by barriebyron** [comment]
if we don't want to add the guided steps, let's do https://app.zenhub.com/workspaces/zkapps-product-eng-6130fedb3b0fc600123d8796/issues/gh/o1-labs/docs2/628 first

**Comment by Saurabhpatil-dev** [comment]
@barriebyron  I would like to work on it. 

Plus, o1js version is now 0.14.* right ?
So, can I use it ?

**Comment by barriebyron** [comment]
@Saurabhpatil-dev  yes, always use the latest version for tutorials, thank you! Please take this up

**Comment by Saurabhpatil-dev** [comment]
Hi @barriebyron ,

Okay, thank you so much!!
Before I start adding steps can you please share any example for my reference ?

Thank You 😃

**Comment by barriebyron** [comment]
@LuffySama-Dev Tutorial 4 has detailed steps https://docs.minaprotocol.com/zkapps/tutorials/zkapp-ui-with-react

I'm not a developer, so I rely on steps to run the code. There are other ways to test the code: download the example files, then `npm run dev` if there is a package.json, and so on.

**Comment by LuffySama-Dev** [comment]
Hi @barriebyron ,

Okay, got it. Let me try and come up  with tutorial as soon as possible.

Thank You 😄

**Comment by LuffySama-Dev** [comment]
Hi @barriebyron ,

I have created this PR  #763 .
Hope this is what you were expecting. 

Thank You 😄
