### ISSUE TITLE
Algolia search doesn’t work for o1js reference

### ISSUE THREAD

**Issue by qwadratic** [o1-labs/docs2#691]
when trying to search o1js-specific terms, the surch runs only over the documentation articles, but not for o1js reference itself. IDK how, but if we index o1js reference as well - it may help developers find reference pages faster

**Comment by barriebyron** [comment]
@MartinMinkov  can you look at search for auto-gen reference docs?

**Comment by MartinMinkov** [comment]
Yep, the [Algolia job](https://github.com/o1-labs/docs2/actions/runs/6679458704/job/18151638973) ran successfully after merging an updated version of the [o1js API docs](https://github.com/o1-labs/docs2/pull/705). 

Should be good now :+1:

**Comment by MartinMinkov** [comment]
Can we close this issue, if everything is working?
