### ISSUE TITLE
Tutorial 9: Recursion zkProgram_wrapper.ts exists in examples folder but not described

### ISSUE THREAD

**Issue by qwadratic** [o1-labs/docs2#698]
This one is related to [Tutorial 9](https://docs.minaprotocol.com/zkapps/tutorials/recursion) 

[zkProgram_wrapper.ts](https://github.com/o1-labs/docs2/blob/main/examples/zkapps/09-recursion/src/zkProgram_wrapper.ts) exists in examples folder, but not mentioned in a tutorial. It does something interesting but I am not sure what exactly.

Should we describe it?

**Comment by barriebyron** [comment]
fixed!
