### ISSUE TITLE
Tutorial 8 tokenSymbol is deprecated

### ISSUE THREAD

**Issue by Pfed-prog** [o1-labs/docs2#708]
So in the `Tutorial 8: Custom Tokens` we set the token symbol (MYTKN) in the init() method.

But there is no hints on how to access the token symbol in a test.

For example, I am able to access the tokenId via `zkAppInstance.tokenId.toString()` which is default at 1.
Meanwhile tokenSymbol is deprecated 
![image](https://github.com/o1-labs/docs2/assets/66903336/012ceefd-071c-43dd-a53b-21545b69fe1d)

**Comment by LuffySama-Dev** [comment]
Hi @Pfed-prog ,

Good Day!! 
Thank you for your issue & patience 😄.

Yes, the tokensymbol is deprecated and we need to use `this.account.tokenSymbol`. 
![Screenshot 2024-02-11 at 7 24 34 PM](https://github.com/o1-labs/docs2/assets/55076843/66de8c45-8f5c-4a50-b552-b84721074a7b)

We can access the tokensymbol in our test like this: `Mina.getAccount(zkAppAddress).tokenSymbol`.

You can find it in use in [main.ts](https://github.com/o1-labs/docs2/blob/main/examples/zkapps/08-custom-tokens/src/main.ts), line number `66`.
![Screenshot 2024-02-11 at 7 20 52 PM](https://github.com/o1-labs/docs2/assets/55076843/135ccb37-fbc3-4131-8d37-5f472768d52f)

Hope this is what you are looking for.

Thank You
Luffy 😄
