### ISSUE TITLE
Document the "zk lightnet" subcommand at docs.minaprotocol.com

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/docs2#726]
Somewhere under the https://docs.minaprotocol.com/zkapps about local development and testing.

Sub-commands added to zkApp CLI in:
https://github.com/o1-labs/zkapp-cli/pull/510

**Comment by barriebyron** [comment]
@shimkiv  can you provide some example commands with a nice overview of a typical test environment for our developers?
The default values are good for a single node, etc etc
Thank you!

**Comment by shimkiv** [comment]
@barriebyron most of the time the defaults should be used.
Examples of commands configuration and use cases I'll add later.

**Comment by barriebyron** [comment]
notes from @garwalsh 
- I'll start with review of Serhii's awesome user stories and then audit the docs for variations on current testing to see what sections of the docs need updating to use the zk lightnet commands 
- Create a draft PR to stage some content that Gar can help me place in the right product-focused docs
