### ISSUE TITLE
Doc Update: Tutorial 09 - Recursion gives error because of publicInputType. 

### ISSUE THREAD

**Issue by LuffySama-Dev** [o1-labs/docs2#739]
![recurrsionTypeIssue01](https://github.com/o1-labs/docs2/assets/55076843/9131a486-6812-4b26-99d7-2e43f0475305)
![recurrsionTypeIssue02](https://github.com/o1-labs/docs2/assets/55076843/5df384ef-6a5b-4fb5-8892-108db95d7ce2)

![recurrsionTypeIssue03](https://github.com/o1-labs/docs2/assets/55076843/7eb7392f-4899-4336-b395-2e5f736af79b)
![recurrsionTypeIssue04](https://github.com/o1-labs/docs2/assets/55076843/bbe5ec48-0926-4657-904b-acba49b33b8c)

In above four images, if you will see we are getting the type error in method as the type of publicInput is not matching to the state.

I am creating a pull request for this issue.

**Comment by Saurabhpatil-dev** [comment]
Hi @barriebyron ,

I have created a Pull request for this : #740

**Comment by Saurabhpatil-dev** [comment]
Also, I went through the main.ts file mentioned in the documentation and seems we are using old version of o1js 0.12.* .

**Comment by barriebyron** [comment]
@Saurabhpatil-dev  yes, please get the latest version and do your awesome updates, thank you!
