### ISSUE TITLE
HF audit zkApp tutorials: verify and run through code for Tutorial 1: Hello World

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/docs2#751]
New issue to verify that the code runs for this tutorial as part of the tutorial audit
Earlier issues may not have satisfied the Definition of Done (DoD) where the code is run against the latest versions of o1js and zkApp CLI

**Comment by LuffySama-Dev** [comment]
Hi @barriebyron ,

Can I take this up ??
Also, to be clear we need to run the test against the latest o1js version of 0.15.1 and check if it's running properly right ?

Thanks Luffy 😃

**Comment by barriebyron** [comment]
Thank you @LuffySama-Dev  yes please! go for it

**Comment by LuffySama-Dev** [comment]
Hi @barriebyron ,

Good Day!! I have been going through the examples, I have couple of questions.

## Questions:
1. The latest version of o1js keeps on upgrading, last month it was 0.15.1 but now It is 0.15.2, so can we make it 0.15.* so until it get's changed to 0.16.* we don't need to worry ??
2. The README.md seems to be same for all the zkapp example. So, should we change and set them up according to the zkApp number ?
3. I have ran the 01-Hello-world example against the latest version on o1js that is 0.15.2 and it's working fine. So, how should I mark this as completed ?

Thanks 😃

**Comment by barriebyron** [comment]
@LuffySama-Dev  thank you thank you!! You are making excellent progress.

- I agree, let's use 0.15.*
- Yes, please make the tutorial READMEs accurate for each tutorial. Add details as you think a developer will need them. Your changes so far are excellent!
- Your efforts are appreciated!

**Comment by LuffySama-Dev** [comment]
Hi @barriebyron ,

Okay, I will follow as we discussed and make future commits.

Thank you 😃
