### ISSUE TITLE
HF audit zkApp tutorials: verify and run through code for Tutorial 2: Private Inputs and Hash Functions

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/docs2#752]
New issue to verify that the code runs for this tutorial as part of the tutorial audit
Earlier issues may not have satisfied the Definition of Done (DoD) where the code is run against the latest versions of o1js and zkApp CLI

**Comment by LuffySama-Dev** [comment]
Hi @barriebyron ,

Can I take this up ??
Also, to be clear we need to run the test against the latest o1js version of 0.15.1 and check if it's running properly right ?

Thanks Luffy 😃

**Comment by barriebyron** [comment]
yes please @LuffySama-Dev  go for it!
