### ISSUE TITLE
HF audit zkApp tutorials: verify and run through code for Tutorial 3: Deploy to a Live Network

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/docs2#753]
HF audit zkApp tutorials: verify and run through code for Tutorial 3: Deploy to a Live Network

New issue to verify that the code runs for this tutorial as part of the tutorial audit
Earlier issues may not have satisfied the Definition of Done (DoD) where the code is run against the latest versions of o1js and zkApp CLI

**Comment by LuffySama-Dev** [comment]
Hi @barriebyron ,

Can I take this up ??
Also, to be clear we need to run the test against the latest o1js version of `0.15.1` and check if it's running properly right ?

Thanks Luffy 😃

**Comment by barriebyron** [comment]
yes please @LuffySama-Dev  go for it! thank you for all of your focus and contributions

**Comment by LuffySama-Dev** [comment]
Hi @barriebyron ,

I have tested steps locally with latest version. 
It is working fine and getting deployed.
We can close this.

Thanks 😃

**Comment by barriebyron** [comment]
thank you
