### ISSUE TITLE
HF audit zkApp tutorials: verify and run through code for Tutorial 8: Custom Tokens

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/docs2#758]
HF audit zkApp tutorials: verify and run through code for Tutorial 8: Custom Tokens

New issue to verify that the code runs for this tutorial as part of the tutorial audit
Earlier issues may not have satisfied the Definition of Done (DoD) where the code is run against the latest versions of o1js and zkApp CLI

**Comment by LuffySama-Dev** [comment]
Hi @barriebyron ,

I would like to work on this.

Thank You 😃

**Comment by barriebyron** [comment]
See #708

**Comment by LuffySama-Dev** [comment]
Hi @barriebyron ,

Done. Issue closed.

Thanks 😃

**Comment by barriebyron** [comment]
thanks @LuffySama-Dev  you are on fire!
