### ISSUE TITLE
HF audit zkApp tutorials: verify and run through code for Tutorial 10: Account Updates

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/docs2#760]
HF audit zkApp tutorials: verify and run through code for Tutorial 10: Account Updates

New issue to verify that the code runs for this tutorial as part of the tutorial audit
Earlier issues may not have satisfied the Definition of Done (DoD) where the code is run against the latest versions of o1js and zkApp CLI

**Comment by LuffySama-Dev** [comment]
Hi @barriebyron ,

Good Day!! 
I would like to work on this.

Thank You 😃

**Comment by barriebyron** [comment]
great @LuffySama-Dev  along with #660  this tutorial needs some love, thank you

**Comment by LuffySama-Dev** [comment]
Hi @barriebyron ,

Thank you so much!! While I am working on it I will check this one too #855 .

Thank you 😃

**Comment by barriebyron** [comment]
Conversation in Discord https://discord.com/channels/484437221055922177/1209120015530463304/1209120015530463304

I have reached out to the visualizer contributor, stay tuned!
