### ISSUE TITLE
Fix email form in the footer to correctly submit 

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/docs2#83]
In the footer, we have an email submission for that lets users sign up for updates. Currently, this form does not do anything when a user submits their email form. 

We need to add some behavior to submit the email to an endpoint for this flow to be finished.

**Comment by ampAlex** [comment]
Hey Martin -- just got this back from our site dev: So if I understand correctly, it sounds like they lifted the form code from [minaprotocol.com](http://minaprotocol.com/) without connecting the plumbing? Do I have that right? The challenge is that the footer form submission on [minaprotocol.com](http://minaprotocol.com/) uses AJAX through a Wordpress form plugin, and it's a component that exists on every page of the site. I don't know if a direct form submission URL exists with this configuration.

**Comment by nicc** [comment]
Further info for debugging and testing can be found [here](https://docs.google.com/document/d/1s9rZte84xjwJh9TjlTwqjg7VgxYhXIXH6nFtGcJH0hc/edit#)
