### ISSUE TITLE
Update custom tokens docs

### ISSUE THREAD

**Issue by garwalsh** [o1-labs/docs2#843]
With the many breaking changes to, and much better API for, token contracts that we just merged or are about to merge, we should update the custom token docs before the next release.

https://docs.minaprotocol.com/zkapps/tutorials/custom-tokens

**Comment by barriebyron** [comment]
@LuffySama-Dev  stay tuned for updates!

**Comment by barriebyron** [comment]
https://app.zenhub.com/workspaces/sdk-6130fedb3b0fc600123d8796/issues/gh/o1-labs/o1js/1274 has the changes coming in future, no need to work right now
