### ISSUE TITLE
Tutorial 10: Dependencies 

### ISSUE THREAD

**Issue by Pfed-prog** [o1-labs/docs2#855]
Gm, learning more about Mina via tutorial 10

I have fixed tutorial locally via moving peerDepencies o1js to dependencies

Because it fixed the following error 
<img width="626" alt="image" src="https://github.com/o1-labs/docs2/assets/66903336/b3274074-b062-4f40-8200-af55c3855540">

I have further removed 'mina-transaction-visualizer'

and commented in `ProofsOnlyZkApp`
//setVerificationKey: Permissions.proof(), 

Also added funding for 2 deployed accounts instead of just one and added signing by deployer key
<img width="641" alt="image" src="https://github.com/o1-labs/docs2/assets/66903336/416b0732-935e-46ca-af7a-1f8b02ffa794">

**Comment by LuffySama-Dev** [comment]
Hi @Pfed-prog ,

I think you faced issues because you were using yarn.
I tested and modified the code using `npm` and it worked fine for me. 
Thanks to your help with the line number `39` we were able to move ahead.

Thank you 😃

**Comment by barriebyron** [comment]
@Pfed-prog  let us know how the updated tutorial works for you! Feel free to open a PR for any required updates, did you want to explore updates for "funding for 2 deployed accounts instead of just one and added signing by deployer key"

**Comment by Pfed-prog** [comment]
omg, thank you very much, great that tutorial is updated :)
